### ISSUE TITLE
Use case: Manually select features to define new geography #531

### ISSUE THREAD

**Issue by gordonje** [HandsOnDataViz/book#100]
First of all, thank you so much for writing and sharing your book. It is a wonderful and helpful resource.

I have a use case wherein a colleague needs to define multiple, non-overlapping custom geographies (calling them "Regions") by selecting adjacent features in a GeoJSON file. The smaller geographies are towns.

My best current plan is to have them define the mapping between the towns and regions in a csv file. Then use mapshaper to select and dissolve those polygons into new ones. Or maybe add a new attribute (e.g., regionID) to the existing features.

I would like to provide my colleague a GUI for doing this, and I'm wondering if mapshaper.org, GeoJSON.io (or some implementation of either of these) would be up to the task. Like I was imagining I could hold shift and click on each feature (or even better drag the cursor across them) to select the towns, then use the console for the next steps.

I would very much appreciate any advice, examples or resources you could provide.

**Comment by JackDougherty** [comment]
Hi James - Thanks for your kind words about the book. If I understand your question correctly, you want to find the simplest way for your colleague to group several towns into larger regions, and add a new attribute (regionID). Here's two options:

Option A: Follow the "Merge Selected Polygons with Join and Dissolve Commands" section of our Mapshaper chapter
https://handsondataviz.org/mapshaper.html#merge-selected-polygons-with-join-and-dissolve-commands
This requires making a spreadsheet of which towns belong to which regions, which is a very good idea if you have numerous towns and several regions. 

Option B: It is possible to manually select and merge small batches of towns into regions in Mapshaper, but you would need to export each region, then re-import all of them and merge together at the end. If you have lots of towns and regions, it would be require multiple steps and it's easy to make mistakes this way (and I know this from experience!) The GUI workflow would go like this:
1) Import your towns GeoJSON into Mapshaper
2) Click the Mapshaper Arrow > Select Features, then click on several towns that form one region, then click the Keep button. All non-selected towns will disappear.
3) Open the Console and type "dissolve" to merge the selected towns into one region
4) Export from MapShaper, rename the file as Region1.geojson to avoid confusing yourself, and start again with step 1.
5) When you've exported all regions, go to Geojson.io, and drag-and-drop all of the regions together (works nicer than Mapshaper for this step). In Geojson.io you can also click Table, then Add a New Column, then manually type in the new RegionID names. Then Save as GeoJSON to export.

**Comment by gordonje** [comment]
I had been missing that "Select Features" option. Thank you for pointing it out.
