### ISSUE TITLE
Alternative to "Paste Special > Transposed" in CH. 4

### ISSUE THREAD

**Issue by dorrajmachai** [HandsOnDataViz/book#101]
Hello,

First, I'd like to say that I am absolutely _loving_ this book! It's very clear and concise and informative. I really appreciate that. 

I don't know if you're already aware of this, but in some cases, the ```Paste special > Transposed``` option does not work in Google Sheets. Instead of pasting transposed data, it does nothing or simply pastes a blank line. I looked it up and [found and implemented this technique](https://support.google.com/docs/thread/66927711/paste-special-transpose-quit-working?hl=en) in order to follow along with the steps in the _"Transpose Rows and Columns"_ section of chapter 4. 

It worked just as well, I presume, as the technique mentioned in the book. I just wanted to share in case others experience this issue. 

I am on (Fedora) Linux and this issue occurred while using Firefox version 109.0. Thank you so much for your time!

EDIT: Fixed post formatting and added a better description of actual results.

**Comment by ilyankou** [comment]
Hi @dorrajmachai and thank you for the tip!

@JackDougherty would you like to add a Tip to [this chapter](https://handsondataviz.org/transpose.html), right after figure 4.4, with something like this:

_Google Sheets also provides a function, `=transpose(<range>)`, which, unlike `Paste special > Transpose`, will prevent you from overwriting existing data in the spreadsheet._

**Comment by JackDougherty** [comment]
Thanks @dorrajmachai - Your tip now appears after the figure [in this chapter](https://handsondataviz.org/transpose.html#transpose), and your name also appears [in our Acknowledgements](https://handsondataviz.org/authors.html#acknowledgements). Apologies for my delay.
