### ISSUE TITLE
Extension option with mapshaper

### ISSUE THREAD

**Issue by linogaliana** [HandsOnDataViz/book#102]
Thanks a lot for your very detailed tutorial on `mapshaper` that reduced my learning curve.

You mention the _issue_ of file extension here:

https://github.com/HandsOnDataViz/book/blob/c6d425de995a6794de990d88289e8058d21c8bd6/13-transform.Rmd#L273C43-L279

I just wanted to let you know it is possible to pass an `extension` option to handle that, e.g.

```python
mapshaper example.shp name='' -o 'outputdir/' format=geojson extension=".geojson"
```

It might be a worth a small footnote or callout box

**Comment by ilyankou** [comment]
Many thanks @linogaliana 

Hi @JackDougherty - would you like to amend the tip (added in bold):

> Tip: In Mapshaper, when you export a file in GeoJSON format, your downloaded file will appear in the .json format. **Type `extension='.geojson'` to the _command line options_ input field just above the Export button to download the file with the _geojson_ extension. Alternatively, simply rename the downloaded** file and change the extension to .geojson format, as shown in Figure [13.9](https://handsondataviz.org/mapshaper.html#fig:mapshaper-json-geojson). This will avoid confusion with other visualization tools in this book that only recognize a properly-named GeoJSON file.

**Comment by JackDougherty** [comment]
Thanks @linogaliana for your input, and I have added your to our book acknowledgements
Thanks @ilyankou for your suggested revision based on the input, which I modified slightly by [rewriting our tip to offer two methods, with an illustration for each one](https://handsondataviz.org/mapshaper.html#fig:mapshaper-export-options)
