### ISSUE TITLE
Can't find map data files

### ISSUE THREAD

**Issue by flywire** [HandsOnDataViz/book#96]
Whare are the csv files?
```
https://handsondataviz.org/peer-3-sample-2.html
...
 var runLayer = omnivore.csv('data.csv', null, customLayer)
...
```

**Comment by ilyankou** [comment]
@flywire 

The repository for the *My Leaflet map*, with the data file, is here: https://github.com/HandsOnDataViz/leaflet-map-simple-instructor-sample
