### ISSUE TITLE
Change base map for story map

### ISSUE THREAD

**Issue by MarkJThomas** [HandsOnDataViz/book#99]
Hiya, I hope you are well,
Thank you so much for the book with information on how to make a story map. It is so easy to follow and I am so happy with the results so far.
I am however trying to change the base map for my story map, I am not well savvied when it comes to java script so not being able to get the results I am after. 
Do you have code or a way that I can do this please? 
All the best,
Mark

**Comment by ilyankou** [comment]
Hi Mark, see [my response](https://github.com/HandsOnDataViz/leaflet-storymaps-with-google-sheets/issues/79#issuecomment-850359849) and let me know if things don't work!
